### ISSUE TITLE
CHEAT_005 Send button

### ISSUE THREAD

**Issue by sw20-tugraz** [sw20-tug/SWT-Afternoon-1#5]
As a user I want the text entered into the text field to be sent to the connected cheating partner’s device when tapping the send button.

**Acceptance criteria:**
- A send button exists positioned (right) next to the text entry field.
- The width of the send button decreases the horizontal width of the text entry field.
- Pressing the send button sends the text entered in the editable text field to the connected cheating partner’s device.
- The editable text field is cleared, i.e., no text is in the field after pressing the send button.

**Comment by Valerionn** [comment]
Sending + Receiving (not displaying sent messages yet)
